# Form implementation generated from reading ui file 'components/pyIVLS_pluginloader.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pyIVLSpluginloader(object):
    def setupUi(self, pyIVLSpluginloader):
        pyIVLSpluginloader.setObjectName("pyIVLSpluginloader")
        pyIVLSpluginloader.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        pyIVLSpluginloader.setEnabled(True)
        pyIVLSpluginloader.resize(600, 377)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyIVLSpluginloader.sizePolicy().hasHeightForWidth())
        pyIVLSpluginloader.setSizePolicy(sizePolicy)
        self.OKButton = QtWidgets.QPushButton(parent=pyIVLSpluginloader)
        self.OKButton.setEnabled(True)
        self.OKButton.setGeometry(QtCore.QRect(400, 340, 89, 25))
        self.OKButton.setObjectName("OKButton")
        self.cancelButton = QtWidgets.QPushButton(parent=pyIVLSpluginloader)
        self.cancelButton.setGeometry(QtCore.QRect(500, 340, 89, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.groupBox = QtWidgets.QGroupBox(parent=pyIVLSpluginloader)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.groupBox.setObjectName("groupBox")
        self.pluginList = QtWidgets.QListWidget(parent=self.groupBox)
        self.pluginList.setGeometry(QtCore.QRect(15, 31, 541, 271))
        self.pluginList.setObjectName("pluginList")

        self.retranslateUi(pyIVLSpluginloader)
        QtCore.QMetaObject.connectSlotsByName(pyIVLSpluginloader)

    def retranslateUi(self, pyIVLSpluginloader):
        _translate = QtCore.QCoreApplication.translate
        pyIVLSpluginloader.setWindowTitle(_translate("pyIVLSpluginloader", "pyIVLS plugin loader"))
        self.OKButton.setText(_translate("pyIVLSpluginloader", "OK"))
        self.cancelButton.setText(_translate("pyIVLSpluginloader", "Cancel"))
        self.groupBox.setTitle(_translate("pyIVLSpluginloader", "Plugins"))
        self.pluginList.setSortingEnabled(True)
