# Integration times
CCS_SERIES_MAX_INT_TIME = 60.0  # 60s is the maximum integration time
CCS_SERIES_MIN_INT_TIME = 0.00001  # 10us is the minimum integration time
CCS_SERIES_DEF_INT_TIME = 0.01  # 10ms is the default integration time

# Spectral limits
CCS175_MIN_WV = 500  # minimum wavelength in nm of spectrometer CCS175
CCS175_MAX_WV = 1000  # maximum wavelength in nm of spectrometer CCS175

# VID AND PID
CCS175_VID = 0x1313
CCS175_PID = 0x8087

# Calibration data sets
CCS_SERIES_CAL_DATA_SET_FACTORY = 0
CCS_SERIES_CAL_DATA_SET_USER = 1

# Status flags
CCS_SERIES_STATUS_SCAN_IDLE = 0x0002  # waiting for new scan
CCS_SERIES_STATUS_SCAN_TRIGGERED = 0x0004  # scan in progress
CCS_SERIES_STATUS_SCAN_START_TRANS = 0x0008  # scan starting
CCS_SERIES_STATUS_SCAN_TRANSFER = 0x0010  # scan done, waiting for data transfer
CCS_SERIES_STATUS_WAIT_FOR_EXT_TRIG = 0x0080  # same as idle, but ext trigger is armed.

# Amplification correction factors
CCS_SERIES_AMP_CORR_FACT_MIN = 0.001
CCS_SERIES_AMP_CORR_FACT_MAX = 1000.0

# Write commands (OUT)
CCS_SERIES_WCMD_WRITE_EEPROM = 0x21
CCS_SERIES_WCMD_INTEGRATION_TIME = 0x23
CCS_SERIES_WCMD_MODUS = 0x24
CCS_SERIES_WCMD_RESET = 0x26

# Read commands (IN)
CCS_SERIES_RCMD_READ_EEPROM = 0x21
CCS_SERIES_RCMD_INTEGRATION_TIME = 0x23
CCS_SERIES_RCMD_PRODUCT_INFO = 0x25
CCS_SERIES_RCMD_GET_STATUS = 0x30
CCS_SERIES_RCMD_GET_ERROR = 0xFF

# Operation Modes
MODUS_INTERN_SINGLE_SHOT = 0
MODUS_INTERN_CONTINUOUS = 1
MODUS_EXTERN_SINGLE_SHOT = 2
MODUS_EXTERN_CONTINUOUS = 3

# Calibration flags
CCS_SERIES_CALIB_VALID_FLAG = 0x5A
CCS_SERIES_USERCAL_VALID_FLAG = 0x5A

# Buffers
CCS_SERIES_SERIAL_NO_LENGTH = 24
CCS_SERIES_NUM_POLY_POINTS = 4
CCS_SERIES_NUM_INTEG_CTRL_BYTES = 6
CCS_SERIES_NUM_VERSION_BYTES = 3

# Specifics
CCS_SERIES_NUM_RAW_PIXELS = 3694
ENDPOINT_0_TRANSFERSIZE = 64
CCS_SERIES_NUM_PIXELS = 3648
NO_DARK_PIXELS = 12
DARK_PIXELS_OFFSET = 16
SCAN_PIXELS_OFFSET = 32
MAX_ADC_VALUE = 0xFFFF

# LLIO constants
LL_DEFAULT_BULK_IN_PIPE = 0x86  # This works and finds scan data
LL_DEFAULT_TIMEOUT = 2000  # This same timeout is used by the orinal drivers

# versions
CCS_SERIES_FIRMWARE_VERSION = 0
CCS_SERIES_HARDWARE_VERSION = 1
